Formatting
VILLASframework/common pull request #101
Opened 2023-02-24 16:42 UTC by Stapelueberflieger

# Motivation for using a formatter
- consistency
- speedup in coding
- better readability

# Highly adjustable
Built a styleguide once, run anywhere: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

# Easy to use
Seamless IDE integration (even possible on autosave) or via single command 

# My personal settings (subject to change)
[My formatting file](https://raw.githubusercontent.com/Stapelueberflieger/format-settings/main/clang-format)
most settings are taken from  [Linus Torvalds style guide](https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst) originally for C but most of his arguments transfer to C++

# See example in commit
https://github.com/VILLASframework/common/commit/d43decef47ed199d46b964afd33a3978b2feecf1 (difficult so read with the compare view)

2023-02-28 08:12 UTC, stv0g commented
Hi @Stapelueberflieger,

could you also add the clang-format config file to the PR?

Having a pre-commit hook which invokes clang-format would be great :-)

2023-02-28 08:13 UTC, stv0g commented
The Torvalds code-style also mentions:

> Outside of comments, documentation and except in Kconfig, spaces are never used for indentation, and the above example is deliberately broken.

I also dislike the usage of spaces for indention. So I would propose to use tabs instead.

2023-03-02 16:16 UTC, IgnoreWarnings commented
I added the formatting file in [62a070f](https://github.com/VILLASframework/common/pull/101/commits/62a070f47abee886c718bb9c55eca20d5327c61c)

I found this regarding git hooks
https://github.com/barisione/clang-format-hooks



> Hi @Stapelueberflieger,
> 
> could you also add the clang-format config file to the PR?
> 
> Having a pre-commit hook which invokes clang-format would be great :-)

2023-03-02 16:19 UTC, IgnoreWarnings commented
> The Torvalds code-style also mentions:
> 
> > Outside of comments, documentation and except in Kconfig, spaces are never used for indentation, and the above example is deliberately broken.
> 
> I also dislike the usage of spaces for indention. So I would propose to use tabs instead.

I personally dont care about this everlasting controversy. Clang-format can easily use tabs over space intendation.

2023-03-02 20:18 UTC, stv0g commented
> I personally dont care about this everlasting controversy. Clang-format can easily use tabs over space intendation.

Lets go with tabs please :) This will also change a lot less lines during the initial re-formatting.

2023-03-10 09:53 UTC, n-eiling commented
I vote for spaces!

2023-03-10 10:00 UTC, n-eiling requested changes

2023-03-10 10:00 UTC, n-eiling commented on lib/base64.cpp
> +        for(std::size_t i = 0; i < input.size() / 3; ++i) {
I prefer a space between `for` and `(`

2023-03-10 10:00 UTC, n-eiling commented on lib/base64.cpp
> +                        padding++;
I would like to always enforce curly brackets and do not allow non bracketed ifs.

2023-03-10 11:19 UTC, IgnoreWarnings commented on lib/base64.cpp
> +        for(std::size_t i = 0; i < input.size() / 3; ++i) {
I added spaces before all control statements. 07f30dcc92acd7078220d3c2cab95af2c4bb0f63

2023-03-10 11:25 UTC, IgnoreWarnings commented on lib/base64.cpp
> +                        padding++;
CMake format will never remove extra curly brackets if you use them, so I recommend adding them on your own. It can automatically add them, however  "Setting this option to true could lead to incorrect code formatting due to clang-format’s lack of complete semantic information. As such, extra care should be taken to review code changes made by this option."

2023-03-10 11:49 UTC, stv0g commented on lib/base64.cpp
> +                        padding++;
I agree with @IgnoreWarnings here. We can agree on making them mandatory. But I would not automate it.

2023-03-10 11:50 UTC, stv0g commented on formatting_example.cpp
> +                       aligator,
I dont feel like the spaced should go here.. There is no parantheses in that line?

2023-03-10 12:36 UTC, n-eiling commented on lib/base64.cpp
> +                        padding++;
ok

2023-03-10 13:58 UTC, IgnoreWarnings commented on formatting_example.cpp
> +                       std::make_unique<struct s>({ 1, 2, 3, 4, 5, 6 }))) {
If closing brackets are not on same line. Which space are you refering to, or the linebreak? @stv0g

2023-03-16 13:24 UTC, IgnoreWarnings commented on formatting_example.cpp
> +                       aligator,
I just used some random snippets as example. They may not be correct.

2023-09-07 11:20 UTC, stv0g commented
Lets close this in favour of #111 

Going with the LLVM code-style is easier to maintain and a more established style in general.

2023-09-07 11:20 UTC, closed without merging