Kernel module loading system and bug fixes of vfio
VILLASframework/common pull request #110
Opened 2023-09-05 21:01 UTC by IgnoreWarnings

Squash recomended before merge.
- feature: Header to specify which kernel modules (vfio support) to load
- Bug fixes: wrong errror messages, bugged region cap
- Quality of use improvements e.g. getter and str()

2023-09-05 21:09 UTC, IgnoreWarnings commented on include/villas/kernel/vfio.hpp
> +/** VFIO Kernel module loader
Specify the fpga type to build string of required kernel modules

2023-09-05 21:14 UTC, IgnoreWarnings commented on include/villas/kernel/vfio.hpp
> +#define FPGA_PCI
Specifies the fpga type to build string of required kernel modules.

2023-09-05 21:14 UTC, IgnoreWarnings commented on lib/kernel/vfio_container.cpp
> -	const char* requiredKernelModules[] = {
This is replaced by include/villas/kernel/vfio.hpp

2023-09-05 21:14 UTC, IgnoreWarnings commented on lib/kernel/vfio_container.cpp
> -		if (kernel::loadModule(module) != 0) {
This is bugged, since the error is also thrown if the kernel module is just already loaded.

2023-09-05 21:14 UTC, IgnoreWarnings commented on lib/kernel/vfio_device.cpp
> +		info.num_regions = VFIO_PCI_CONFIG_REGION_INDEX + 1;
Not all vfio devices are pci, thous having different region amounts than VFIO_PCI_CONFIG_REGION_INDEX

2023-09-05 21:14 UTC, IgnoreWarnings commented on lib/kernel/vfio_device.cpp
> -	for (size_t i = 0; i < info.num_regions && i < 8; i++) {
This is pci specific.

2023-09-06 06:40 UTC, stv0g requested changes

2023-09-06 06:40 UTC, stv0g commented on include/villas/kernel/vfio.hpp
> + * Systems, EONERC SPDX-License-Identifier: Apache-2.0
```suggestion
 * SPDX-FileCopyrightText: 2017 Institute for Automation of Complex Power Systems, RWTH Aachen University
 * SPDX-License-Identifier: Apache-2.0
```

2023-09-06 06:40 UTC, stv0g commented on include/villas/kernel/vfio.hpp
> +//#define FPGA_PLATFORM
```suggestion
// TODO: Move to cmake args
// #define FPGA_PLATFORM
```

Please also consider moving this into `config.hpp.in` using a `#cmakedefine`

2023-09-06 06:40 UTC, stv0g commented on include/villas/kernel/vfio.hpp
> +    #endif // KERNEL_MODULE_VFIO_IOMMU_TYPE1
```suggestion
#if defined(KERNEL_MODULE_VFIO)
    "vfio",
#endif // KERNEL_MODULE_VFIO_PCI

#if defined(KERNEL_MODULE_VFIO_PCI)
    "vfio_pci",
#endif // KERNEL_MODULE_VFIO_PCI
    
#if defined(KERNEL_MODULE_VFIO_IOMMU_TYPE1)
    "vfio_iommu_type1"
#endif // KERNEL_MODULE_VFIO_IOMMU_TYPE1
```

2023-09-06 06:40 UTC, stv0g commented on include/villas/kernel/vfio_device.hpp
> +	std::string get_name() { return name; };
```suggestion
	std::string getName() { return name; };
```

2023-09-06 06:40 UTC, stv0g commented on include/villas/memory_manager.hpp
> +		std::string str()
```suggestion
		std::string toString()
```

2023-09-06 06:40 UTC, stv0g commented on lib/kernel/vfio_device.cpp
> +	if (pci_device != 0){
```suggestion
	if (pci_device != 0) {
```

2023-09-06 06:40 UTC, stv0g commented on lib/kernel/vfio_device.cpp
> +	}else{ info.num_regions = 1; }
```suggestion
	} else
		info.num_regions = 1;
```

2023-09-06 06:40 UTC, stv0g commented on lib/kernel/vfio_container.cpp
> +		kernel::loadModule(module);
I would try to have a second look at this.
If the module does not appear to be loaded, maybe its because its loaded asynchronously in the background? If thats the case we are running into the danger of a race condition. We should figure out why its bugged..

2023-09-06 06:40 UTC, stv0g commented on lib/kernel/vfio_container.cpp
> +static std::array<std::string, EXTENSION_SIZE> construct_vfio_extension_str() {
```suggestion
static
std::array<std::string, EXTENSION_SIZE> construct_vfio_extension_str() {
```

Please keep the coding style :)

2023-09-06 06:41 UTC, stv0g commented
On a general note: please try to follow the 7 rules of a good Git commit message:

https://cbea.ms/git-commit/#seven-rules

2023-09-06 13:27 UTC, n-eiling commented on include/villas/kernel/vfio.hpp
> +//#define FPGA_PLATFORM
I think this is fine for now - as long as there is no regression when not setting this.

2023-09-06 13:29 UTC, n-eiling commented on lib/kernel/vfio_container.cpp
> +static std::array<std::string, EXTENSION_SIZE> construct_vfio_extension_str() {
We should revisit #101

2023-09-06 13:32 UTC, n-eiling commented on lib/kernel/vfio_container.cpp
> +		kernel::loadModule(module);
he is saying that this returns and error when the module is already loaded. We should at least add a note and an issue that this has to be changed in the future.

2023-09-06 13:32 UTC, n-eiling commented on lib/kernel/vfio_device.cpp
> +	}else{ info.num_regions = 1; }
#101

2023-09-06 13:33 UTC, n-eiling commented
> On a general note: please try to follow the 7 rules of a good Git commit message:
> 
> https://cbea.ms/git-commit/#seven-rules

not a problem if we squash as requested.

2023-09-06 13:33 UTC, n-eiling commented
please rebase and fix the formatting issues :)

2023-09-06 15:39 UTC, stv0g commented
I think you also need to squash locally as we cant do this in GitHub

2023-09-06 22:59 UTC, IgnoreWarnings commented on lib/kernel/vfio_container.cpp
> +		kernel::loadModule(module);
TLDR: The function is not bugged, I will readd the error handling. 
 The console message "Kernel module {} already loaded..." is just misleading. A child process loads the kernelmodule, therefore loadModule() returns "already loaded" even on first load.

2023-09-06 23:05 UTC, IgnoreWarnings commented
> I think you also need to squash locally as we cant do this in GitHub

You can select squash and merge in github.

2023-09-06 23:14 UTC, IgnoreWarnings commented on include/villas/kernel/vfio.hpp
> +//#define FPGA_PLATFORM
As my comment suggests, a cmake define would be much cleaner. I will look up the docs.

2023-09-06 23:26 UTC, IgnoreWarnings commented on lib/kernel/vfio_device.cpp
> +	}else{ info.num_regions = 1; }
the spaces are good, but the else on a single line is not.

2023-09-07 09:30 UTC, n-eiling commented on lib/kernel/vfio_device.cpp
> +	}else{ info.num_regions = 1; }
please fix the spaces at least

2023-09-07 09:32 UTC, n-eiling requested changes
please fix the spaces in vfio_device.cpp

2023-09-07 16:46 UTC, stv0g approved these changes
Thanks :)

2023-09-07 16:46 UTC, stv0g commented
You only need to fix the DCO sign-offs and then we can merge it

2023-09-07 18:24 UTC, IgnoreWarnings commented
@n-eiling  your requested change is [59c9f74](https://github.com/VILLASframework/common/pull/110/commits/59c9f7407567f920519addd9367ffedb0ae04a73).  I dont see where i can resolve.

2023-09-08 08:11 UTC, n-eiling approved these changes

2023-09-08 08:12 UTC, merged