Nice C++
VILLASframework/common pull request #94
Opened 2022-12-21 10:52 UTC by stv0g

2022-12-21 10:53 UTC, stv0g commented
Yay, reduced the code base by about 100 lines :)

2023-01-04 09:55 UTC, n-eiling requested changes

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/pci.cpp
> +	std::istringstream(line) >> std::hex >> start >> end >> flags;
I find scanf much more readable in terms of how the input should actually be formated. Doesn't C++ or libfmt have something similar?

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/pci.cpp
> +uint32_t Device::readHostBar(unsigned bar) const
We don't really every want to access other BARs than BAR0. But I guess this is fine. Can you add a comment explaining what the parameter is? Maybe rename it barNum.

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/pci.cpp
> +	log->debug("Host BAR: start={:#x}, end={:#x}, flags={:#x}", start, end, flags);
please also output the bar size

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/pci.cpp
> +void Device::rewriteBar(unsigned bar)
rename parameter to barNum

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/pci.cpp
> +	file.seekg(PCI_BASE_ADDRESS_0 + sizeof(uint32_t) * bar);
This should use PCI_BASE_ADDRESS_0 , _1, _2 etc and not calculate like this. BAR sizes are not always 4 byte afaik

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/pci.cpp
> +void Device::writeBar(uint32_t addr, unsigned bar)
rename to barNum

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/pci.cpp
> +	file.seekp(PCI_BASE_ADDRESS_0 + sizeof(uint32_t) * bar);
Use PCI_BASE_ADDRESS_N

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/pci.cpp
> +	return file;
does the destructor close the file? Can you document the lifetime of the returned object?

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/vfio_container.cpp
> +		throw SystemError("Failed to attach VFIO group {} to container fd {}",
I had issues with issues with exceptions not being catched not being output. Is there any problem with also logging?

2023-01-04 09:55 UTC, n-eiling commented on lib/kernel/vfio_container.cpp
> +		throw SystemError("Failed to set IOMMU type of container");
same, I would keep the log output

2023-01-05 10:58 UTC, stv0g commented on lib/kernel/pci.cpp
> +	std::istringstream(line) >> std::hex >> start >> end >> flags;
Unfortunately not. `lifmt` is output only. And the C++ way is the `std::istringstream`. Which I actually find easier to read than `scanf`.

I think it only feels od because we have been used to the bad way C is doing it..

2023-01-05 10:59 UTC, stv0g commented on lib/kernel/pci.cpp
> +uint32_t Device::readHostBar(unsigned bar) const
Good point! I will rename the parameter. I also added a default value of `0` for our use case. But I could forsee some other uses in the future where we have multiple BARs

2023-01-05 11:15 UTC, stv0g commented on lib/kernel/pci.cpp
> +	file.seekg(PCI_BASE_ADDRESS_0 + sizeof(uint32_t) * bar);
Mhh, I checked the PCIe spec. The same registers are in fact used for 32 and 64 Bit BARs.
To differentiate whether a BAR is 64 or 32 bit white the lower bits of the BAR are used.
Bit 2-1 encode the BAR type where a value of 2 indentifies a 64 bit bar.

So instead of `sizeof(uint32_t)` we should probably use `is64BitBar ? sizeof(uint64_t) : sizeof(uint32_t)`.

I will implement a fix for this in a way that we never the BAR type.

See also:
- https://wiki.osdev.org/PCI#Base_Address_Registers
- https://en.wikipedia.org/wiki/PCI_configuration_space
- https://astralvx.com/storage/2020/11/PCI_Express_Base_4.0_Rev0.3_February19-2014.pdf (Section 7.5.2.1., Page 585)
- https://stackoverflow.com/a/65585616

2023-01-05 11:16 UTC, stv0g commented on lib/kernel/vfio_container.cpp
> +		throw SystemError("Failed to attach VFIO group {} to container fd {}",
Are you missing  a `try { } catch () {}` block in your `main()` function?

2023-01-05 11:25 UTC, stv0g commented on lib/kernel/pci.cpp
> +	file.seekg(PCI_BASE_ADDRESS_0 + sizeof(uint32_t) * bar);
I forgot to mention that the offsets are hard coded in the include file:

https://elixir.bootlin.com/linux/v4.4/source/include/uapi/linux/pci_regs.h#L85

2023-01-05 11:25 UTC, n-eiling commented on lib/kernel/pci.cpp
> +	std::istringstream(line) >> std::hex >> start >> end >> flags;
I strongly disagree. Format strings are way easier to handle here, because the formatting is the key information in this line. E.g., the separating character is not visible in your code at all. Also std::scanf and std::printf are perfectly legal C++ and are still widely used in C++ code. I see no reason for this change at all.

2023-01-05 11:26 UTC, n-eiling commented on lib/kernel/pci.cpp
> +	file.seekg(PCI_BASE_ADDRESS_0 + sizeof(uint32_t) * bar);
why not use the constants that are actually containing the address you are looking for?

2023-01-05 11:27 UTC, stv0g commented on lib/kernel/pci.cpp
> +	return file;
Yes the destructor closes the file. I will add some comment to the code

See: https://en.cppreference.com/w/cpp/io/basic_fstream

2023-01-05 11:27 UTC, n-eiling commented on lib/kernel/vfio_container.cpp
> +		throw SystemError("Failed to attach VFIO group {} to container fd {}",
In my case there were exception occuring in the catch block.

2023-01-05 11:32 UTC, stv0g commented on lib/kernel/pci.cpp
> +	return file;
Its actually a bit more complicated:

`std::fstream` has a move constructor which is used here. On return of a `std::fstream` C++ performs return value optimization and move-construct the instances from within the function into the local variable of the caller.

Man, this are evil C++ details -.-

See here for an explanation: https://stackoverflow.com/a/4986802

2023-01-05 11:47 UTC, stv0g commented on lib/kernel/pci.cpp
> +	file.seekg(PCI_BASE_ADDRESS_0 + sizeof(uint32_t) * bar);
Because this would require an ugly switch/case block and it would not improve portability as 64 bit BARs are anyway broken in the current code (also not used by our Vivado PCIe bridge config).

2023-01-05 11:51 UTC, stv0g commented on lib/kernel/pci.cpp
> +	std::istringstream(line) >> std::hex >> start >> end >> flags;
I think the C++ variant looks much more elegant.. Your code is 37 lines vs 22 for mine :D

2023-01-05 12:00 UTC, stv0g commented on lib/kernel/pci.cpp
> +	file.seekp(PCI_BASE_ADDRESS_0 + sizeof(uint32_t) * bar);
Okay, I added a new Macro named `PCI_BASE_ADDRESS_N(n)` ^^

2023-01-11 08:46 UTC, stv0g commented on lib/kernel/pci.cpp
> +	log->debug("Host BAR: start={:#x}, end={:#x}, flags={:#x}", start, end, flags);
Done

2023-01-12 10:05 UTC, n-eiling requested changes

2023-01-12 10:05 UTC, n-eiling commented on lib/kernel/pci.cpp
> +	file.seekg(PCI_BASE_ADDRESS_0 + sizeof(uint32_t) * bar);
use your new macro?

2023-01-12 17:27 UTC, stv0g commented on lib/kernel/pci.cpp
> +	std::istringstream(line) >> std::hex >> start >> end >> flags;
Okay, I reverted it back to `sscanf `as you proposed.

2023-01-13 09:58 UTC, n-eiling approved these changes

2023-01-13 09:58 UTC, merged